// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encrypted_app_ticket.proto

#ifndef PROTOBUF_encrypted_5fapp_5fticket_2eproto__INCLUDED
#define PROTOBUF_encrypted_5fapp_5fticket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace Sc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_encrypted_5fapp_5fticket_2eproto();
void protobuf_AssignDesc_encrypted_5fapp_5fticket_2eproto();
void protobuf_ShutdownFile_encrypted_5fapp_5fticket_2eproto();

class EncryptedAppTicket;

// ===================================================================

class EncryptedAppTicket : public ::google::protobuf::MessageLite {
 public:
  EncryptedAppTicket();
  virtual ~EncryptedAppTicket();

  EncryptedAppTicket(const EncryptedAppTicket& from);

  inline EncryptedAppTicket& operator=(const EncryptedAppTicket& from) {
    CopyFrom(from);
    return *this;
  }

  static const EncryptedAppTicket& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EncryptedAppTicket* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EncryptedAppTicket* other);

  // implements Message ----------------------------------------------

  EncryptedAppTicket* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EncryptedAppTicket& from);
  void MergeFrom(const EncryptedAppTicket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ticket_version_no = 1;
  inline bool has_ticket_version_no() const;
  inline void clear_ticket_version_no();
  static const int kTicketVersionNoFieldNumber = 1;
  inline ::google::protobuf::uint32 ticket_version_no() const;
  inline void set_ticket_version_no(::google::protobuf::uint32 value);

  // optional uint32 crc_encryptedticket = 2;
  inline bool has_crc_encryptedticket() const;
  inline void clear_crc_encryptedticket();
  static const int kCrcEncryptedticketFieldNumber = 2;
  inline ::google::protobuf::uint32 crc_encryptedticket() const;
  inline void set_crc_encryptedticket(::google::protobuf::uint32 value);

  // optional uint32 cb_encrypteduserdata = 3;
  inline bool has_cb_encrypteduserdata() const;
  inline void clear_cb_encrypteduserdata();
  static const int kCbEncrypteduserdataFieldNumber = 3;
  inline ::google::protobuf::uint32 cb_encrypteduserdata() const;
  inline void set_cb_encrypteduserdata(::google::protobuf::uint32 value);

  // optional uint32 cb_encrypted_appownershipticket = 4;
  inline bool has_cb_encrypted_appownershipticket() const;
  inline void clear_cb_encrypted_appownershipticket();
  static const int kCbEncryptedAppownershipticketFieldNumber = 4;
  inline ::google::protobuf::uint32 cb_encrypted_appownershipticket() const;
  inline void set_cb_encrypted_appownershipticket(::google::protobuf::uint32 value);

  // optional bytes encrypted_ticket = 5;
  inline bool has_encrypted_ticket() const;
  inline void clear_encrypted_ticket();
  static const int kEncryptedTicketFieldNumber = 5;
  inline const ::std::string& encrypted_ticket() const;
  inline void set_encrypted_ticket(const ::std::string& value);
  inline void set_encrypted_ticket(const char* value);
  inline void set_encrypted_ticket(const void* value, size_t size);
  inline ::std::string* mutable_encrypted_ticket();
  inline ::std::string* release_encrypted_ticket();
  inline void set_allocated_encrypted_ticket(::std::string* encrypted_ticket);

  // @@protoc_insertion_point(class_scope:Sc.EncryptedAppTicket)
 private:
  inline void set_has_ticket_version_no();
  inline void clear_has_ticket_version_no();
  inline void set_has_crc_encryptedticket();
  inline void clear_has_crc_encryptedticket();
  inline void set_has_cb_encrypteduserdata();
  inline void clear_has_cb_encrypteduserdata();
  inline void set_has_cb_encrypted_appownershipticket();
  inline void clear_has_cb_encrypted_appownershipticket();
  inline void set_has_encrypted_ticket();
  inline void clear_has_encrypted_ticket();

  ::google::protobuf::uint32 ticket_version_no_;
  ::google::protobuf::uint32 crc_encryptedticket_;
  ::google::protobuf::uint32 cb_encrypteduserdata_;
  ::google::protobuf::uint32 cb_encrypted_appownershipticket_;
  ::std::string* encrypted_ticket_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_encrypted_5fapp_5fticket_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_encrypted_5fapp_5fticket_2eproto();
  #endif
  friend void protobuf_AssignDesc_encrypted_5fapp_5fticket_2eproto();
  friend void protobuf_ShutdownFile_encrypted_5fapp_5fticket_2eproto();

  void InitAsDefaultInstance();
  static EncryptedAppTicket* default_instance_;
};
// ===================================================================


// ===================================================================

// EncryptedAppTicket

// optional uint32 ticket_version_no = 1;
inline bool EncryptedAppTicket::has_ticket_version_no() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EncryptedAppTicket::set_has_ticket_version_no() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EncryptedAppTicket::clear_has_ticket_version_no() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EncryptedAppTicket::clear_ticket_version_no() {
  ticket_version_no_ = 0u;
  clear_has_ticket_version_no();
}
inline ::google::protobuf::uint32 EncryptedAppTicket::ticket_version_no() const {
  return ticket_version_no_;
}
inline void EncryptedAppTicket::set_ticket_version_no(::google::protobuf::uint32 value) {
  set_has_ticket_version_no();
  ticket_version_no_ = value;
}

// optional uint32 crc_encryptedticket = 2;
inline bool EncryptedAppTicket::has_crc_encryptedticket() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EncryptedAppTicket::set_has_crc_encryptedticket() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EncryptedAppTicket::clear_has_crc_encryptedticket() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EncryptedAppTicket::clear_crc_encryptedticket() {
  crc_encryptedticket_ = 0u;
  clear_has_crc_encryptedticket();
}
inline ::google::protobuf::uint32 EncryptedAppTicket::crc_encryptedticket() const {
  return crc_encryptedticket_;
}
inline void EncryptedAppTicket::set_crc_encryptedticket(::google::protobuf::uint32 value) {
  set_has_crc_encryptedticket();
  crc_encryptedticket_ = value;
}

// optional uint32 cb_encrypteduserdata = 3;
inline bool EncryptedAppTicket::has_cb_encrypteduserdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EncryptedAppTicket::set_has_cb_encrypteduserdata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EncryptedAppTicket::clear_has_cb_encrypteduserdata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EncryptedAppTicket::clear_cb_encrypteduserdata() {
  cb_encrypteduserdata_ = 0u;
  clear_has_cb_encrypteduserdata();
}
inline ::google::protobuf::uint32 EncryptedAppTicket::cb_encrypteduserdata() const {
  return cb_encrypteduserdata_;
}
inline void EncryptedAppTicket::set_cb_encrypteduserdata(::google::protobuf::uint32 value) {
  set_has_cb_encrypteduserdata();
  cb_encrypteduserdata_ = value;
}

// optional uint32 cb_encrypted_appownershipticket = 4;
inline bool EncryptedAppTicket::has_cb_encrypted_appownershipticket() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EncryptedAppTicket::set_has_cb_encrypted_appownershipticket() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EncryptedAppTicket::clear_has_cb_encrypted_appownershipticket() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EncryptedAppTicket::clear_cb_encrypted_appownershipticket() {
  cb_encrypted_appownershipticket_ = 0u;
  clear_has_cb_encrypted_appownershipticket();
}
inline ::google::protobuf::uint32 EncryptedAppTicket::cb_encrypted_appownershipticket() const {
  return cb_encrypted_appownershipticket_;
}
inline void EncryptedAppTicket::set_cb_encrypted_appownershipticket(::google::protobuf::uint32 value) {
  set_has_cb_encrypted_appownershipticket();
  cb_encrypted_appownershipticket_ = value;
}

// optional bytes encrypted_ticket = 5;
inline bool EncryptedAppTicket::has_encrypted_ticket() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EncryptedAppTicket::set_has_encrypted_ticket() {
  _has_bits_[0] |= 0x00000010u;
}
inline void EncryptedAppTicket::clear_has_encrypted_ticket() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void EncryptedAppTicket::clear_encrypted_ticket() {
  if (encrypted_ticket_ != &::google::protobuf::internal::kEmptyString) {
    encrypted_ticket_->clear();
  }
  clear_has_encrypted_ticket();
}
inline const ::std::string& EncryptedAppTicket::encrypted_ticket() const {
  return *encrypted_ticket_;
}
inline void EncryptedAppTicket::set_encrypted_ticket(const ::std::string& value) {
  set_has_encrypted_ticket();
  if (encrypted_ticket_ == &::google::protobuf::internal::kEmptyString) {
    encrypted_ticket_ = new ::std::string;
  }
  encrypted_ticket_->assign(value);
}
inline void EncryptedAppTicket::set_encrypted_ticket(const char* value) {
  set_has_encrypted_ticket();
  if (encrypted_ticket_ == &::google::protobuf::internal::kEmptyString) {
    encrypted_ticket_ = new ::std::string;
  }
  encrypted_ticket_->assign(value);
}
inline void EncryptedAppTicket::set_encrypted_ticket(const void* value, size_t size) {
  set_has_encrypted_ticket();
  if (encrypted_ticket_ == &::google::protobuf::internal::kEmptyString) {
    encrypted_ticket_ = new ::std::string;
  }
  encrypted_ticket_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EncryptedAppTicket::mutable_encrypted_ticket() {
  set_has_encrypted_ticket();
  if (encrypted_ticket_ == &::google::protobuf::internal::kEmptyString) {
    encrypted_ticket_ = new ::std::string;
  }
  return encrypted_ticket_;
}
inline ::std::string* EncryptedAppTicket::release_encrypted_ticket() {
  clear_has_encrypted_ticket();
  if (encrypted_ticket_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = encrypted_ticket_;
    encrypted_ticket_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EncryptedAppTicket::set_allocated_encrypted_ticket(::std::string* encrypted_ticket) {
  if (encrypted_ticket_ != &::google::protobuf::internal::kEmptyString) {
    delete encrypted_ticket_;
  }
  if (encrypted_ticket) {
    set_has_encrypted_ticket();
    encrypted_ticket_ = encrypted_ticket;
  } else {
    clear_has_encrypted_ticket();
    encrypted_ticket_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Sc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_encrypted_5fapp_5fticket_2eproto__INCLUDED
